# Generated by Django 2.2.2 on 2019-07-09 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=8)),
                ('university', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=32)),
                ('degree', models.CharField(max_length=16)),
                ('grade', models.CharField(max_length=8)),
                ('course_name', models.CharField(max_length=32)),
                ('course_id', models.CharField(max_length=16)),
                ('course_num', models.CharField(max_length=16)),
                ('course_subname', models.CharField(max_length=32)),
                ('grade_point', models.IntegerField()),
                ('length_course', models.IntegerField()),
                ('length_lab', models.IntegerField()),
                ('time', models.CharField(max_length=32)),
                ('course_content', models.CharField(max_length=32)),
                ('classroom', models.CharField(max_length=16)),
                ('professor', models.CharField(max_length=32)),
                ('max_student', models.CharField(max_length=8)),
                ('current_student', models.IntegerField()),
                ('etc', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ShortenName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('memo', models.CharField(max_length=30, null=True)),
                ('todo_type', models.CharField(max_length=10)),
                ('done', models.BooleanField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todos.Course')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_altname',
            field=models.ManyToManyField(blank=True, to='todos.ShortenName'),
        ),
    ]
