# Generated by Django 2.2.2 on 2019-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
                ('professor', models.CharField(max_length=20)),
                ('todo_type', models.CharField(max_length=10)),
                ('done', models.BooleanField()),
            ],
        ),
    ]
