# Generated by Django 2.2.2 on 2019-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190630_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
